version: "3.9"

services:
  taskapi:
    build: .
    image: taskapi
    depends_on:
      - db
    ports:
      - "8080:8080"
    secrets:
      - DBUSER
      - DBPASS
  
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: taskinator
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DBPASS
    volumes:
      - type: bind
        source: ./db/mysql_define.sql
        target: /docker-entrypoint-initdb.d/define_schema.sql
    secrets:
    - DBUSER
    - DBPASS

secrets:
  DBUSER:
    file: .local/db_user.txt
  DBPASS:
    file: .local/db_pass.txt
