CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,
    admin BOOLEAN NOT NULL,
    token VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS devices (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    token VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(64) NOT NULL,
    deviceid BIGINT NOT NULL,
    state SMALLINT,
    PRIMARY KEY (id),
    FOREIGN KEY (deviceid) REFERENCES devices(id)
);

CREATE TABLE IF NOT EXISTS responses (
    id BIGINT NOT NULL AUTO_INCREMENT,
    taskid BIGINT NOT NULL,
    state SMALLINT,
    PRIMARY KEY (id),
    FOREIGN KEY (taskid) REFERENCES tasks(id)
);

CREATE TABLE IF NOT EXISTS controls (
    userid BIGINT NOT NULL,
    deviceid BIGINT NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id),
    FOREIGN KEY (deviceid) REFERENCES devices(id)
);
